/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { SnakeScore, SnakeScoreInterface } from "../SnakeScore";

const _abi = [
  {
    inputs: [],
    name: "ScoreMustBePositive",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "previousBest",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "attemptedScore",
        type: "uint256",
      },
    ],
    name: "ScoreMustIncrease",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "previousBest",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newBest",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ScoreUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "getBestScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "score",
        type: "uint256",
      },
    ],
    name: "submitScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101bd806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806368b0e1fa1461003b578063aff0b29714610076575b600080fd5b61006461004936600461013e565b6001600160a01b031660009081526020819052604090205490565b60405190815260200160405180910390f35b61008961008436600461016e565b61008b565b005b806000036100ac5760405163a17a024560e01b815260040160405180910390fd5b336000908152602081905260409020548082116100ea57604051634461944d60e01b8152600481018290526024810183905260440160405180910390fd5b33600081815260208181526040918290208590558151848152908101859052428183015290517f4e129cd592c4928775615d37d8f0f5a5e1257dec2f17b8b5fe34881b83b1cdc59181900360600190a25050565b60006020828403121561015057600080fd5b81356001600160a01b038116811461016757600080fd5b9392505050565b60006020828403121561018057600080fd5b503591905056fea264697066735822122035a45566e9a8d0cd5ba1ee0d1bd4b2e396fd521ce6a446de809e92b1046e9b7e64736f6c63430008180033";

type SnakeScoreConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SnakeScoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SnakeScore__factory extends ContractFactory {
  constructor(...args: SnakeScoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SnakeScore & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SnakeScore__factory {
    return super.connect(runner) as SnakeScore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SnakeScoreInterface {
    return new Interface(_abi) as SnakeScoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SnakeScore {
    return new Contract(address, _abi, runner) as unknown as SnakeScore;
  }
}
