/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SnakeScore } from "./SnakeScore";
export * as factories from "./factories";
export { SnakeScore__factory } from "./factories/SnakeScore__factory";
